config/routes.rb
Rails.application.routes.draw do
  root 'purchases#index'
  resources :purchases

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
  end

  def update
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/purchases/edit.html.erb
<p> This is the [edit] View file </p>

app/views/purchases/index.html.erb
jhgg

app/views/purchases/new.html.erb
<%= form_tag do %>

<div>
<%= label_tag 'name', "What's your name?" %><br />
<%= text_field_tag 'name' %>
</div>

<div>
<%= label_tag 'quantity', "How many did you get?" %><br />
<%= number_field_tag 'quantity' %>
</div>

<div>
<%= label_tag 'notes', "Notes" %><br />
<%= text_field_tag 'notes' %>
<div/>

<div>
<%= label_tag 'added_by', "Who add this?"%><br />
<%= text_field_tag 'added_by' %>
<div/>


<div>
<%= label_tag 'email', "Your email Address?"%><br />
<%= text_field_tag 'email'%>
</div>

<div>
<%= label_tag 'phone', "Your Phone Number?"%><br />
<%= text_field_tag 'phone'%>
</div>

<div>
<%=label_tag 'priotiy', "Priority"%><br />
<%the_array = ['High', 'Medium', 'Low']%>
<%= select_tag 'priority', options_for_select(Array[*the_array.collect {|v,i| [v,the_array.index(v)] }])%>
</div>

<div>
<%= submit_tag %>
</div>

<% end %>

app/views/purchases/show.html.erb
<%= form_tag purchases_path %>
This is the show template of the Shopping app.